<?php
class Config {
    private static ?array $cfg = null;

    public static function isInstalled(): bool {
        return file_exists(ARMA_CONFIG);
    }

    public static function load(): array {
        if (self::$cfg === null) {
            if (!self::isInstalled()) {
                throw new RuntimeException('Sistema não instalado. Acesse /install/');
            }
            self::$cfg = require ARMA_CONFIG;
        }
        return self::$cfg;
    }

    public static function get(string $key, $default = null) {
        $c = self::load();
        return $c[$key] ?? $default;
    }

    public static function write(array $data): bool {
        $php = "<?php\n// Auto-generated by A.R.M.A installer. Do not edit by hand.\nreturn " . var_export($data, true) . ";\n";
        return (bool) file_put_contents(ARMA_CONFIG, $php, LOCK_EX);
    }
}
